"""hrms face leave payroll

Revision ID: 6368bc812453
Revises: 04d228688419
Create Date: 2026-07-02 01:24:10.367406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6368bc812453'
down_revision: Union[str, None] = '04d228688419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('leave_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('max_days_per_year', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('carry_forward', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('employee_ensemble_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ensemble_vector', postgresql.BYTEA(), nullable=False),
    sa.Column('embedding_count', sa.Integer(), nullable=False),
    sa.Column('embedding_version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'embedding_version')
    )
    op.create_index(op.f('ix_employee_ensemble_embeddings_user_id'), 'employee_ensemble_embeddings', ['user_id'], unique=False)
    op.create_table('face_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('embedding_vector', postgresql.BYTEA(), nullable=False),
    sa.Column('reference_image_url', sa.Text(), nullable=False),
    sa.Column('embedding_version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('image_quality_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('face_angle', sa.String(length=20), nullable=True),
    sa.Column('expression', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_embeddings_user_id'), 'face_embeddings', ['user_id'], unique=False)
    op.create_table('leave_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('pending_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'leave_type_id', 'year')
    )
    op.create_index(op.f('ix_leave_balances_leave_type_id'), 'leave_balances', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_user_id'), 'leave_balances', ['user_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leavestatus', native_enum=False), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_leave_type_id'), 'leave_requests', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_user_id'), 'leave_requests', ['user_id'], unique=False)
    op.create_table('salary_structures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('da', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conveyance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('medical_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('special_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('overtime_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pf_deduction_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pt_deduction_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('tds_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_structures_user_id'), 'salary_structures', ['user_id'], unique=False)
    op.create_table('payroll_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('salary_structure_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('days_present', sa.Integer(), nullable=False),
    sa.Column('days_absent', sa.Integer(), nullable=False),
    sa.Column('days_leave_paid', sa.Integer(), nullable=False),
    sa.Column('days_leave_unpaid', sa.Integer(), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('basic_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('da_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overtime_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_employee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pt_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tds_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lop_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'processed', 'approved', 'paid', 'cancelled', name='payrollstatus', native_enum=False), nullable=False),
    sa.Column('payslip_url', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', 'year')
    )
    op.create_index(op.f('ix_payroll_records_user_id'), 'payroll_records', ['user_id'], unique=False)
    op.add_column('attendance', sa.Column('face_confidence', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('employee_code', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('joining_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('employment_type', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('aadhaar_number', sa.String(length=12), nullable=True))
    op.add_column('users', sa.Column('pan_number', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('bank_account_number', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('bank_ifsc', sa.String(length=11), nullable=True))
    op.add_column('users', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('documents_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'users', ['employee_code'])
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'documents_metadata')
    op.drop_column('users', 'bank_name')
    op.drop_column('users', 'bank_ifsc')
    op.drop_column('users', 'bank_account_number')
    op.drop_column('users', 'pan_number')
    op.drop_column('users', 'aadhaar_number')
    op.drop_column('users', 'status')
    op.drop_column('users', 'employment_type')
    op.drop_column('users', 'joining_date')
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'employee_code')
    op.drop_column('users', 'phone')
    op.drop_column('attendance', 'face_confidence')
    op.drop_index(op.f('ix_payroll_records_user_id'), table_name='payroll_records')
    op.drop_table('payroll_records')
    op.drop_index(op.f('ix_salary_structures_user_id'), table_name='salary_structures')
    op.drop_table('salary_structures')
    op.drop_index(op.f('ix_leave_requests_user_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_leave_type_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_leave_balances_user_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_leave_type_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_face_embeddings_user_id'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_index(op.f('ix_employee_ensemble_embeddings_user_id'), table_name='employee_ensemble_embeddings')
    op.drop_table('employee_ensemble_embeddings')
    op.drop_table('leave_types')
    op.drop_table('departments')
    # ### end Alembic commands ###
